test_p1 (__main__.Test.test_p1) ... ok
test_p2 (__main__.Test.test_p2) ... ok
test_p3 (__main__.Test.test_p3) ... ERROR
test_p4 (__main__.Test.test_p4) ... ERROR
test_p5 (__main__.Test.test_p5) ... ok
test_p6 (__main__.Test.test_p6) ... ERROR

======================================================================
ERROR: test_p3 (__main__.Test.test_p3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\twkot\Desktop\pp1\05-Test1\mock\check.py", line 27, in test_p3
    import p3
ModuleNotFoundError: No module named 'p3'

======================================================================
ERROR: test_p4 (__main__.Test.test_p4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\twkot\Desktop\pp1\05-Test1\mock\check.py", line 32, in test_p4
    import p4
ModuleNotFoundError: No module named 'p4'

======================================================================
ERROR: test_p6 (__main__.Test.test_p6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\twkot\Desktop\pp1\05-Test1\mock\check.py", line 43, in test_p6
    import p6
  File "c:\Users\twkot\Desktop\pp1\05-Test1\mock\p6.py", line 15, in <module>
    z=summation(x,y)
      ^^^^^^^^^^^^^^
  File "c:\Users\twkot\Desktop\pp1\05-Test1\mock\p6.py", line 9, in summation
    sum_all=sum+int(a[i])
                    ~^^^
TypeError: 'int' object is not subscriptable

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=3)
